import { Inter,IBM_Plex_Sans } from "next/font/google";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import SideBar from "./components/SideBar";
import Footer from "./components/Footer";
import styles from "./layout.module.css"

config.autoAddCss = false;
import "./globals.css";
import HeaderDynamic from "./components/Headers/HeaderDynamic";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const ibmPlexSans = IBM_Plex_Sans({
  variable: "--font-ibm",
  subsets: ["latin"],
});

export const metadata = {
  title: "NewsFoundry",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html  lang="fr" >
		<body suppressHydrationWarning className={`${inter.variable} ${ibmPlexSans.variable}`}>
			<div className={styles.container}>
				<HeaderDynamic />
				<div className={styles.content}>
					<SideBar />
					<main className={styles.main}>
						{children}
					</main>
				</div>
				<Footer />
			</div>
		</body>
    </html>
  );
}
